title: ♡ alexine 
author: Alexine  
email: alexine.leport@gmail.com 
url: https://jalexine.github.io 
baseurl: "/" 
description: > # text 
  <p> Here's my only fixed address <br> I'm a traveler, bioinformatics MSc student & I run a small clothing business <br> <br> > i've just updated my date me link ♡ <br>  <br> <span style="color: white;"> <span style="font-size: 40px;">️ ☣ </span> </span>  <a href="https://open.spotify.com/user/auwtkox85ovn7ahyyvuv64gql?si=cded6bf4e4ac4a8f" style="color: #f0166f;">
    <span style="color: white;">  listen to my sick playlists </span> </a> <span style="color: white;"> <span style="font-size: 40px;">️ ☣ </span> </span> <br> <br> interest : bio/ml, computer arch, theology, philosophy, music, arts, poetry, opera, theater, horror, books, hiking, experiencing and pushing the boundaries of my understanding <br> <br> pure hate : journalism, ideology, <a href="/assets/badfaith.pdf" target="_blank" style="color: #f0166f;">this kind of bad faith</a>, authority, advertising, 2-factor authentication and Windows   <br> <br> ↓ will update one day  </p>

permalink: /:slug.html

favicon: "icons8-disco-ball-96.png" 

remote_theme: riggraz/no-style-please 

theme_config:
  appearance: "auto" # "light", "dark" or "auto"
  back_home_text: ".." 
  date_format: "%Y-%m-%d" 
  show_description: true

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  reco:
    output: true
